### PR TITLE
Working runit services

### PR DESCRIPTION
**Pull request by Toilal**
Hi @chrert, thanks for working on mailinabox dockerization.

I'm on it too, and your Dockerfile seems very good as it should fix issues i've encoutered with services.

1) The removall of upstart doesn't work because runit depends on it.
2 ) `RUN rm -f /tmp/mailinabox_apt_package_list.txt` is not required, because it will be removed at the very last step of the Dockerfile.

I'll build this and give it a try on my own server.

### CODE REVIEW

**Comment by Toilal** [comment]
Problems i've noticed, maybe you are already aware about them, but ...

Before starting `init.sh` container, there's a repeating message `/usr/bin/sv not found` displayed.

After starting the `init.sh` :

- FPM:
```
[23-Feb-2015 18:59:23] ERROR: An another FPM instance seems to already listen on /var/run/php5-fpm.sock
[23-Feb-2015 18:59:23] ERROR: FPM initialization failed
```

- fail2ban 
```
2015-02-23 18:59:23,201 fail2ban.server : INFO   Starting Fail2ban v0.8.11
2015-02-23 18:59:23,202 fail2ban.server : ERROR  Unable to create PID file: [Errno 2] No such file or directory: '/var/run/fail2ban/fail2ban.pid'
2015-02-23 18:59:23,202 fail2ban.server : ERROR  Could not start server: Unable to bind socket /var/run/fail2ban/fail2ban.sock
2015-02-23 18:59:23,202 fail2ban.server : ERROR  Unable to remove PID file: [Errno 2] No such file or directory: '/var/run/fail2ban/fail2ban.pid'
2015-02-23 18:59:23,202 fail2ban.server : INFO   Exiting Fail2ban
```

**Comment by Toilal** [comment]
When I start to run the container, it fails : 

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 8
*** Runit exited with status 127
sh: 1: /usr/bin/sv: not found
sh: 1: /usr/bin/sv: not found
*** Killing all processes...
```

You may have received mail notifications about other errors, please ignore them, it was wrong... I had commented `RUN DEBIAN_FRONTEND=noninteractive apt-get remove -y upstart`, so many services were starting twice ...

**Comment by Toilal** [comment]
I don't think it possible to remove upstart package, because runit depends on it. Removing upstart also removes runit.

**Comment by Toilal** [comment]
Maybe you could simply remove `init`/`init.d` scripts that have runit script.

**Comment by chrert** [comment]
Thanks for your contribution.
I will have a look at it this weekend and hopefuly I get everything working soon!

**Comment by Toilal** [comment]
Thanks, i'll keep working on this branch, I start to understand how the whole thing works :)

**Comment by Toilal** [comment]
It's working, but it still need some work on `bind9` runit script.

```
FAILED: sv restart bind9
-----------------------------------------
timeout: down: bind9: 1s, normally up, want up
-----------------------------------------
```

There's also a problem with openkdmi : 

```
named: error while loading shared libraries: liblwres.so.90: cannot open shared object file: Permission denied
opendkim: smfi_opensocket() failed
named: error while loading shared libraries: liblwres.so.90: cannot open shared object file: Permission denied
opendkim: smfi_opensocket() failed
```

Also, instead of using `sv` to control runit service, it would be better create symlink `/usr/bin/sv` to `/etc/init.d/<service>` for each runit service, see [What about LSB init scripts compliance](http://smarden.org/runit/faq.html#lsb) in runit FAQ.

Another minor issue : Some runit services are created before required files are installed by setup script. This floods the docker container logs of services failing to start for various reason.

**Comment by chrert** [comment]
I wasn't aware of the fact that runit supports lsb init scripts. I think that will solve most of the issues I had!

**Comment by Toilal** [comment]
@chrert sorry, but it doesn't really support lsb init scripts. Creating the symlink only make `service service_name start` or `/etc/init.d/service_name start` works by redirecting to `sv` command. 

Writing custom scripts for runit is still required.

**Comment by Toilal** [comment]
There's an issue when running docker container with `--privileged` flag. bind9 can't run, because of a permission issue.

This can be reproduced without runing the startup script, just after creating the container.

```
root@1bb894097afe:/# named --help
named: error while loading shared libraries: liblwres.so.90: cannot open shared object file: Permission denied
```

So i'll sugest to remove the `--privileged` flag for now ...

I think this is related to https://github.com/docker/docker/issues/7318, and there are other issues when searching for `error while loading shared libraries` in docker repository.

**Comment by chrert** [comment]
@Toilal That looks very good! Thanks for your work!
There are still some issues: Sometimes not all services are started on restart. I will have a look at that!

As soon as everything is working, I will make a PR to the main repo!

**Pull request merged**
